routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Administrator\PostController;
use App\Http\Controllers\Administrator\AdminController;
use App\Http\Controllers\Administrator\PagesController;
use App\Http\Controllers\Administrator\CategoryController;
use App\Http\Controllers\Administrator\Logs\AuditLogsController;
use App\Http\Controllers\Administrator\Logs\SystemLogsController;
use App\Http\Controllers\Administrator\Account\SettingsController;

Route::middleware('role:admin')->group(function () {
    Route::get('/dashboard', [AdminController::class, 'admin'])->middleware('auth');

    $menu = theme()->getMenu();
    array_walk($menu, function ($val) {
        if (isset($val['path'])) {
            $route = Route::get($val['path'], [PagesController::class, 'index']);

            // Exclude documentation from auth middleware
            if (!Str::contains($val['path'], 'documentation')) {
                $route->middleware('auth');
            }
        }
    });
    // Account pages
    Route::prefix('account')->group(function () {
        Route::get('settings', [SettingsController::class, 'index'])->name('settings.index');
        Route::get('overview', [SettingsController::class, 'overview'])->name('settings.overview');
        Route::put('settings', [SettingsController::class, 'update'])->name('settings.update');
        Route::put('settings/email', [SettingsController::class, 'changeEmail'])->name('settings.changeEmail'); 
        Route::put('settings/password', [SettingsController::class, 'changePassword'])->name('settings.changePassword');
        Route::post('settings', [SettingsController::class, 'statistical']);
    });

    // Category account pages
    Route::prefix('category')->group(function () {
        Route::get('index', [CategoryController::class, 'index'])->name('category.index');
        Route::get('add', [CategoryController::class, 'create'])->name('category.create');
        Route::get('edit/{id}', [CategoryController::class, 'edit'])->name('category.edit');

        Route::post('add', [CategoryController::class, 'store'])->name('category.store');
        Route::put('edit/{id}', [CategoryController::class, 'update'])->name('category.update');
        Route::post('destroy/{id}', [CategoryController::class, 'destroy'])->name('category.destroy');
        Route::post('status/{id}', [CategoryController::class, 'update_status'])->name('category.status');
    });

    // Account game pages
    Route::prefix('post')->group(function () {
        Route::get('index', [PostController::class, 'index'])->name('post.index');
        Route::get('add', [PostController::class, 'create'])->name('post.create');
        Route::get('edit/{id}', [PostController::class, 'edit'])->name('post.edit');

        Route::post('add', [PostController::class, 'store'])->name('post.store');
        Route::put('edit/{id}', [PostController::class, 'update'])->name('post.update');
        Route::post('destroy/{id}', [PostController::class, 'destroy'])->name('post.destroy');
        Route::post('status/{id}', [PostController::class, 'update_status'])->name('post.status');
    });
    // Logs pages
    Route::prefix('log')->group(function () {
        Route::resource('system', SystemLogsController::class)->only(['index', 'destroy']);
        Route::resource('audit', AuditLogsController::class)->only(['index', 'destroy']);
    });

    //Setting
    Route::prefix('setting')->group(function () {
        Route::get('index', [SettingController::class, 'edit'])->name('setting.edit');
        Route::post('update', [SettingController::class, 'update'])->name('setting.update');
    });
});
        

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Auth\SocialiteLoginController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('index');
Route::get('/article-detail/{id}', [HomeController::class, 'article_detail'])->name('article-detail');
Route::get('/contact', [HomeController::class, 'contact']);
Route::get('/category', [HomeController::class, 'category']);
Route::get('/about-us', [HomeController::class, 'about']);

Route::get('/auth/redirect/{provider}', [SocialiteLoginController::class, 'redirect']);

require __DIR__.'/auth.php';

app/Models/UserInfo.php
<?php

namespace App\Models;

use App\Core\Traits\SpatieLogsActivity;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class UserInfo extends Model
{
    use SpatieLogsActivity;

    /**
     * Prepare proper error handling for url attribute
     *
     * @return string
     */
    public function getAvatarUrlAttribute()
    {
        // if file avatar exist in storage folder
        $avatar = public_path(Storage::url($this->avatar));
        if (is_file($avatar) && file_exists($avatar)) {
            // get avatar url from storage
            return Storage::url($this->avatar);
        }

        // check if the avatar is an external url, eg. image from google
        if (filter_var($this->avatar, FILTER_VALIDATE_URL)) {
            return $this->avatar;
        }

        // no avatar, return blank avatar
        return asset(theme()->getMediaUrlPath().'avatars/blank.png');
    }

    /**
     * User info relation to user model
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Unserialize values by default
     *
     * @param $value
     *
     * @return mixed|null
     */
    public function getCommunicationAttribute($value)
    {
        // test to un-serialize value and return as array
        $data = @unserialize($value);
        if ($data !== false) {
            return $data;
        } else {
            return null;
        }
    }
}

resources/views/layout/demo8/aside/_base.blade.php
<!--begin::Aside-->
<div
	id="kt_aside"
	class="aside"
	data-kt-drawer="true"
	data-kt-drawer-name="aside"
	data-kt-drawer-activate="{default: true, lg: false}"
	data-kt-drawer-overlay="true"
	data-kt-drawer-width="{default:'200px', '300px': '250px'}"
	data-kt-drawer-direction="start"
	data-kt-drawer-toggle="#kt_aside_mobile_toggle"
	>

    <!--begin::Aside Toolbarl-->
    <div class="aside-toolbar flex-column-auto" id="kt_aside_toolbar">
        {{ theme()->getView('layout/aside/_toolbar') }}
        <!--end::Aside user-->
    </div>
    <!--end::Aside Toolbarl-->

    <!--begin::Aside menu-->
	<div class="aside-menu flex-column-fluid">
		{{ theme()->getView('layout/aside/_menu') }}
    </div>
    <!--end::Aside menu-->

    <!--begin::Footer-->
    <div class="aside-footer flex-column-auto py-5" id="kt_aside_footer">
        <a href="{{ theme()->getPageUrl('#') }}" class="btn btn-custom btn-primary w-100" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-dismiss-="click" title="{{ theme()->getOption('product', 'tooltips/docs-and-components') }}">
            <span class="btn-label">
                Docs & Components
            </span>
            {!! theme()->getSvgIcon("icons/duotune/general/gen005.svg", "btn-icon svg-icon-2") !!}
        </a>
    </div>
    <!--end::Footer-->
</div>
<!--end::Aside-->

resources/views/layout/demo8/aside/_menu.blade.php
<!--begin::Aside Menu-->
@php
    $menu = bootstrap()->getAsideMenu();
    \App\Core\Adapters\Menu::filterMenuPermissions($menu->items);
@endphp

<div
    class="hover-scroll-overlay-y px-2 my-5 my-lg-5"
    id="kt_aside_menu_wrapper"

    data-kt-scroll="true"
    data-kt-scroll-height="auto"
    data-kt-scroll-dependencies="{default: '#kt_aside_toolbar, #kt_aside_footer', lg: '#kt_header, #kt_aside_toolbar, #kt_aside_footer'}"
    data-kt-scroll-wrappers="#kt_aside_menu"
    data-kt-scroll-offset="5px"
>
    <!--begin::Menu-->
    <div class="menu menu-column menu-title-gray-800 menu-state-title-primary menu-state-icon-primary menu-state-bullet-primary menu-arrow-gray-500" id="#kt_aside_menu" data-kt-menu="true">
        {!! $menu->build() !!}
    </div>
    <!--end::Menu-->
</div>
<!--end::Aside Menu-->

resources/views/layout/demo8/aside/_toolbar.blade.php
<!--begin::User-->
<div class="aside-user d-flex align-items-sm-center justify-content-center py-5">
    <!--begin::Symbol-->
    <div class="symbol symbol-50px">
        <img src="{{ auth()->user()->avatar_url }}" alt=""/>
    </div>
    <!--end::Symbol-->

    <!--begin::Wrapper-->
    <div class="aside-user-info flex-row-fluid flex-wrap ms-5">
        <!--begin::Section-->
        <div class="d-flex">
            <!--begin::Info-->
            <div class="flex-grow-1 me-2">
                <!--begin::Username-->
                <a href="#" class="text-white text-hover-primary fs-6 fw-bold">{{ auth()->user()->name }}</a>
                <!--end::Username-->

                <!--begin::Description-->
                <span class="text-gray-600 fw-bold d-block fs-8 mb-1">Python Dev</span>
                <!--end::Description-->

                <!--begin::Label-->
                <div class="d-flex align-items-center text-success fs-9">
                    <span class="bullet bullet-dot bg-success me-1"></span>online
                </div>
                <!--end::Label-->
            </div>
            <!--end::Info-->

            <!--begin::User menu-->
            <div class="me-n2">
                <!--begin::Action-->
                <a href="#" class="btn btn-icon btn-sm btn-active-color-primary mt-n2" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-start" data-kt-menu-overflow="true">
                    {!! theme()->getSvgIcon("icons/duotune/coding/cod001.svg", "svg-icon-muted svg-icon-1") !!}
                </a>

                {{ theme()->getView('partials/topbar/_user-menu', array('language-menu-placement' => 'right-start', 'subscription-menu-placement' => 'right-start')) }}
                <!--end::Action-->
            </div>
            <!--end::User menu-->
        </div>
        <!--end::Section-->
    </div>
    <!--end::Wrapper-->
</div>
<!--end::User-->

<!--begin::Aside search-->
<div class="aside-search py-5">
    {{ theme()->getView('layout/search/_base') }}
</div>
<!--end::Aside search-->